language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999

after_success:
  - julia -e 'include(Pkg.dir("Highlights", "docs", "travis.jl"))'
  - julia -e 'include(Pkg.dir("Highlights", "test", "coverage.jl"))'
