language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

# Use the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#     - julia: nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path="."))'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
