# Write the tree_sitter_*_jll package names registered in General to src/language_jlls.jl.

import Pkg

function general_registry()
    Pkg.Registry.update("General")
    for reg in Pkg.Registry.reachable_registries()
        reg.name == "General" && return reg
    end
    error("General registry not installed")
end

function language_jlls(reg)
    names = String[]
    for (_, entry) in reg
        name = entry.name
        if startswith(name, "tree_sitter_") &&
           endswith(name, "_jll") &&
           name != "tree_sitter_jll"
            push!(names, name)
        end
    end
    return sort!(names)
end

function main()
    path = joinpath(@__DIR__, "..", "..", "src", "language_jlls.jl")
    names = language_jlls(general_registry())
    open(path, "w") do io
        println(io, "# Generated by scripts/languages/languages.jl. Do not edit by hand.")
        println(io)
        println(io, "const LANGUAGE_JLLS = [")
        foreach(name -> println(io, "    ", repr(name), ","), names)
        println(io, "]")
    end
    println("Wrote $(length(names)) packages to $path")
end

main()
