definition(::Type{GitHubTheme}) = Dict(
    :name => "GitHub Theme",
    :comments => "Based on the Rouge 'GitHub' theme.",
    :style => S"bg: f8f8f8",
    :tokens => Dict(
        :comment             => S"fg: 999988; italic",
        :comment_multiline   => S"fg: 999988; italic",
        :comment_preproc     => S"fg: 999999; bold",
        :comment_single      => S"fg: 999988; italic",
        :comment_special     => S"fg: 999999; italic; bold",

        :error               => S"fg: a61717; bg: e3d2d2",

        :generic             => S"fg: 000000",
        :generic_deleted     => S"fg: 000000; bg: ffdddd",
        :generic_emph        => S"fg: 000000; italic",
        :generic_error       => S"fg: aa0000",
        :generic_heading     => S"fg: 999999",
        :generic_inserted    => S"fg: 000000; bg: ddffdd",
        :generic_output      => S"fg: 888888",
        :generic_prompt      => S"fg: 555555",
        :generic_strong      => S"bold",
        :generic_subheading  => S"fg: aaaaaa",
        :generic_traceback   => S"fg: aa0000",

        :keyword             => S"fg: 000000; bold",
        :keyword_constant    => S"fg: 000000; bold",
        :keyword_declaration => S"fg: 000000; bold",
        :keyword_namespace   => S"fg: 000000; bold",
        :keyword_pseudo      => S"fg: 000000; bold",
        :keyword_reserved    => S"fg: 000000; bold",
        :keyword_type        => S"fg: 445588; bold",

        :number              => S"fg: 009999",
        :number_float        => S"fg: 009999",
        :number_hex          => S"fg: 009999",
        :number_integer      => S"fg: 009999",
        :number_integer_long => S"fg: 009999",
        :number_oct          => S"fg: 009999",

        :string              => S"fg: d14",
        :string_backtick     => S"fg: d14",
        :string_char         => S"fg: d14",
        :string_doc          => S"fg: d14",
        :string_double       => S"fg: d14",
        :string_escape       => S"fg: d14",
        :string_heredoc      => S"fg: d14",
        :string_interpol     => S"fg: d14",
        :string_other        => S"fg: d14",
        :string_regex        => S"fg: 009926",
        :string_single       => S"fg: d14",
        :string_symbol       => S"fg: 990073",

        :name                => S"fg: 008080",
        :name_attribute      => S"fg: 008080",
        :name_builtin        => S"fg: 0086b3",
        :name_builtin_pseudo => S"fg: 999999",
        :name_class          => S"fg: 445588; bold",
        :name_constant       => S"fg: 008080",
        :name_decorator      => S"fg: 3c5d5d; bold",
        :name_entity         => S"fg: 800080",
        :name_exception      => S"fg: 990000; bold",
        :name_function       => S"fg: 990000; bold",
        :name_label          => S"fg: 990000; bold",
        :name_namespace      => S"fg: 555555",
        :name_tag            => S"fg: 000080",

        :variable            => S"fg: 008080",
        :variable_class      => S"fg: 008080",
        :variable_global     => S"fg: 008080",
        :variable_instance   => S"fg: 008080",

        :operator            => S"fg: 000000; bold",
        :operator_word       => S"fg: 000000; bold",

        :text                => S"bg: f8f8f8",
        :text_whitespace     => S"fg: bbbbbb",
    )
)
