definition(::Type{MonokaiTheme}) = Dict(
    :name => "Monokai",
    :description => "A style that mimics the Monokai color scheme.",
    :comments => "Based on the Monokai theme from Pygments.",
    :style => S"bg: 272822; fg: 49483e",
    :tokens => Dict(
        :comment                   => S"fg: 75715e",
        :comment_multiline         => S"",
        :comment_preproc           => S"",
        :comment_single            => S"",
        :comment_special           => S"",

        :error                     => S"fg: 960050; bg: 1e0010",

        :generic                   => S"",
        :generic_deleted           => S"fg: f92672",
        :generic_emph              => S"italic",
        :generic_error             => S"",
        :generic_heading           => S"",
        :generic_inserted          => S"fg: a6e22e",
        :generic_output            => S"",
        :generic_prompt            => S"",
        :generic_strong            => S"bold",
        :generic_subheading        => S"fg: 75715e",
        :generic_traceback         => S"",

        :keyword                   => S"fg: 66d9ef",
        :keyword_constant          => S"",
        :keyword_declaration       => S"",
        :keyword_namespace         => S"fg: f92672",
        :keyword_pseudo            => S"",
        :keyword_reserved          => S"",
        :keyword_type              => S"",

        :literal                   => S"fg: ae81ff",
        :literal_date              => S"fg: e6db74",

        :name                      => S"fg: f8f8f2",
        :name_attribute            => S"fg: a6e22e",
        :name_builtin              => S"",
        :name_builtin_pseudo       => S"",
        :name_class                => S"fg: a6e22e",
        :name_constant             => S"fg: 66d9ef",
        :name_decorator            => S"fg: a6e22e",
        :name_entity               => S"",
        :name_exception            => S"fg: a6e22e",
        :name_function             => S"fg: a6e22e",
        :name_label                => S"",
        :name_namespace            => S"",
        :name_other                => S"fg: a6e22e",
        :name_property             => S"",
        :name_tag                  => S"fg: f92672",
        :name_variable             => S"",
        :name_variable_class       => S"",
        :name_variable_global      => S"",
        :name_variable_instance    => S"",

        :number                    => S"fg: ae81ff",
        :number_float              => S"",
        :number_hex                => S"",
        :number_integer            => S"",
        :number_integer_long       => S"",
        :number_oct                => S"",

        :operator                  => S"fg: f92672",
        :operator_word             => S"",

        :other                     => S"",

        :punctuation               => S"fg: f8f8f2",

        :string                    => S"fg: e6db74",
        :string_backtick           => S"",
        :string_char               => S"",
        :string_doc                => S"",
        :string_double             => S"",
        :string_escape             => S"fg: ae81ff",
        :string_heredoc            => S"",
        :string_interpol           => S"",
        :string_other              => S"",
        :string_regex              => S"",
        :string_single             => S"",
        :string_symbol             => S"",

        :text                      => S"fg: f8f8f2",

        :whitespace                => S"",
    )
)
