definition(::Type{TangoTheme}) = Dict(
    :name => "Tango Theme",
    :description => "A theme inspired by the Tango Icon Theme Guidelines.",
    :comments => "Based on Tango theme from Pygments.",
    :style => S"fg: f8f8f8",
    :tokens => Dict(
        :comment                => S"italic; fg: 8f5902",
        :comment_multiline      => S"italic; fg: 8f5902",
        :comment_preproc        => S"italic; fg: 8f5902",
        :comment_single         => S"italic; fg: 8f5902",
        :comment_special        => S"italic; fg: 8f5902",

        :error                  => S"fg: a40000; bg: ef2929",

        :generic                => S"fg: 000000",
        :generic_deleted        => S"fg: a40000",
        :generic_emph           => S"italic; fg: 000000",
        :generic_error          => S"fg: ef2929",
        :generic_heading        => S"bold; fg: 000080",
        :generic_inserted       => S"fg: 00a000",
        :generic_output         => S"italic; fg: 000000",
        :generic_prompt         => S"fg: 8f5902",
        :generic_strong         => S"bold; fg: 000000",
        :generic_subheading     => S"bold; fg: 800080",
        :generic_traceback      => S"bold; fg: a40000",

        :keyword                => S"bold; fg: 204a87",
        :keyword_constant       => S"bold; fg: 204a87",
        :keyword_declaration    => S"bold; fg: 204a87",
        :keyword_namespace      => S"bold; fg: 204a87",
        :keyword_pseudo         => S"bold; fg: 204a87",
        :keyword_reserved       => S"bold; fg: 204a87",
        :keyword_type           => S"bold; fg: 204a87",

        :literal                => S"fg: 000000",
        :literal_date           => S"fg: 000000",

        :name                   => S"fg: 000000",
        :name_attribute         => S"fg: c4a000",
        :name_builtin           => S"fg: 204a87",
        :name_builtin_pseudo    => S"fg: 3465a4",
        :name_class             => S"fg: 000000",
        :name_constant          => S"fg: 000000",
        :name_decorator         => S"bold; fg: 5c35cc",
        :name_entity            => S"fg: ce5c00",
        :name_exception         => S"bold; fg: cc0000",
        :name_function          => S"fg: 000000",
        :name_label             => S"fg: f57900",
        :name_namespace         => S"fg: 000000",
        :name_other             => S"fg: 000000",
        :name_property          => S"fg: 000000",
        :name_tag               => S"bold; fg: 204a87",
        :name_variable          => S"fg: 000000",
        :name_variable_class    => S"fg: 000000",
        :name_variable_global   => S"fg: 000000",
        :name_variable_instance => S"fg: 000000",

        :number                 => S"bold; fg: 0000cf",
        :number_float           => S"bold; fg: 0000cf",
        :number_hex             => S"bold; fg: 0000cf",
        :number_integer         => S"bold; fg: 0000cf",
        :number_integer_long    => S"bold; fg: 0000cf",
        :number_oct             => S"bold; fg: 0000cf",

        :operator               => S"bold; fg: ce5c00",
        :operator_word          => S"bold; fg: 204a87",

        :other                  => S"fg: 000000",

        :punctuation            => S"bold; fg: 000000",

        :string                 => S"fg: 4e9a06",
        :string_backtick        => S"fg: 4e9a06",
        :string_char            => S"fg: 4e9a06",
        :string_doc             => S"italic; fg: 8f5902",
        :string_double          => S"fg: 4e9a06",
        :string_escape          => S"fg: 4e9a06",
        :string_heredoc         => S"fg: 4e9a06",
        :string_interpol        => S"fg: 4e9a06",
        :string_other           => S"fg: 4e9a06",
        :string_regex           => S"fg: 4e9a06",
        :string_single          => S"fg: 4e9a06",
        :string_symbol          => S"fg: 4e9a06",

        :text                   => S"",

        :whitespace             => S"underline; fg: f8f8f8",
    )
)
