@theme VisualStudioTheme Dict(
    :name => "Visual Studio",
    :description => "Based on the theme from MS Visual Studio.",
    :comments => "Based on the Visual Studio theme from Pygments.",
    :style => S"bg: ffffff",
    :tokens => Dict(
        COMMENT            => S"fg: 008000",
        COMMENT_PREPROC    => S"fg: 0000ff",
        KEYWORD            => S"fg: 0000ff",
        OPERATOR_WORD      => S"fg: 0000ff",
        KEYWORD_TYPE       => S"fg: 2b91af",
        NAME_CLASS         => S"fg: 2b91af",
        STRING             => S"fg: a31515",
        GENERIC_HEADING    => S"bold",
        GENERIC_SUBHEADING => S"bold",
        GENERIC_EMPH       => S"italic",
        GENERIC_STRONG     => S"bold",
        GENERIC_PROMPT     => S"bold",
        ERROR              => S"bg: ff0000; fg: ffffff",
        TEXT               => S"",
    ),
)
